# Salt Project - UCL BENV0117 Dissertation
# Shinydashboard

# app.R ----
library(shinydashboard); library(shiny); library(shinydashboardPlus); 
library(shinyWidgets); library(shinythemes); # library(flexdashboard)
# library(SaltsR)
source("R.R"); source("modules.R"); source("auth.R"); # source("R/Home.R")


# header ----


# sidebar ----
sidebar <- sidebarMenu(
  menuItem("Home", icon = icon("home"), tabName = "home"),
  menuItem("Salt tools", icon = icon("database"), tabName = "tools"),
  menuItem("Risks", icon = icon("chart-area"), tabName = "analysis"),
  
  br()
)

# body ----
body <-  
  tabItems(
    # Home tab UI ----
    tabItem(
      tabName = "home",
      fluidRow(
        column(1, img(src = "SaltsR_hexsticker.png", height = 100, width = 90, align = "left")), # "SaltsR-logo.png" # SaltsR_hexsticker.png
        column(7, h1("Salt weathering tool"), 
               p("This is a data science tool under development to aid 
                 scientists, researchers, conservators and managers of cultural heritage that are
                 interested in protecting heritage from salt weathering.")),
        column(2, img(src = "UCL_ISH_logo.jpg", height = 90, width = 90, align = "right")), #
        column(2, tags$img(height = "90px", width = "90px", alt = "KIK-IRPA Koninklijk Instituut voor het Kunstpatrimonium - Institut Royal du Patrimoine Artistique", src = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/KIK-IRPA_logo.svg/1200px-KIK-IRPA_logo.svg.png"))),
      br(),
      fluidRow(
        shinydashboard::box(
          title = "Introduction", status = "primary", 
          collapsible = TRUE, collapsed = FALSE, width = 12, 
          solidHeader = TRUE, background = "light-blue",
          column(7, 
                 p("Salt formation is a major challenge for the preservation of many cultural heritage sites, buildings and objects. Salt formation can occur on many cultural heritage objects that are porous such as stone, mortar, plaster, bricks, cement and other materials. The damage is often referred to as 'weathering' and can affect both old and modern buildings. The damage that results to cultural heritage is physical processes due to the stresses generated by the crystallisation and re-crystallisation cycles and this is determined by the chemistry of the salt mixtures. The types of heritage at risk of damage included buildings, statues, monuments, ceramics and objects. The damage affects the structure and appearance of heritage materials and can create costs for interventive conservation following damage or introducing measures such as air conditioning to prevent damage. Having tools to aid knowledge of how salt mixtures will behave under different climatic conditions helps planning. ")),
          column(2,
                 tags$img(
                   height = "150px", 
                   alt = "SEM image of sodium chloride ©KIK-IRPA", 
                   src = "https://predict.kikirpa.be/wp-content/uploads/_pda/2020/02/NaCl00001-cut.jpg"),
                 p("SEM images of salts under magnification ©KIK-IRPA")),
          column(2, 
                 tags$img(
                   height = "150px", alt = "Salt Project",
                   src = "https://predict.kikirpa.be/wp-content/uploads/2020/02/DROP500001_result-crop-2.jpg")), 
        )),
      fluidRow(
        shinydashboard::box(
          title = "Resources", status = "primary", 
          collapsible = TRUE, collapsed = TRUE, width = 12, 
          solidHeader = TRUE, background = "light-blue",
          h3("Online resources"),
          p("KIK-IRPA PREDICT: https://predict.kikirpa.be/"),
          p("Salt Wiki: https://www.saltwiki.net/index.php/Home"), 
          p("ECOS – RUNSALT :  http://science.sdf-eu.org/runsalt/ Price (2000) and Bionda (2005)."),
          p("MDCS / Monument Diagnosis and Conservation System :  https://mdcs.monumentenkennis.nl/"),
          h3("References"), 
          p("Sebastiaan Godts, Roald Hayen, and Hilde De Clercq. Investigating salt decay of stonematerials related to the environment, a case study in the st. james church in liège,belgium.Studies in Conservation, 62(6):329–342, Aug 2017."), 
          p("Clifford Price. Salt damage in porous materials: a threat to the cultural heritage.Archaeology International, 1(0), Nov 1997."), 
          p("- Bionda, D., 2005. RUNSALT - A graphical user interface to the ECOS thermodynamic model for the prediction of the behaviour of salt mixtures under changing climate conditions. http://science.sdf-eu.org/runsalt/"), 
          p("
- Price, C. A. (Ed.), 2000. An expert chemical model for determining the environmental conditions needed to prevent salt damage in porous materials. European Commission Research Report No 11, (Protection and Conservation of European Cultural Heritage). Archetype Publications, London."),
br()), 
      )), 
# Data tab UI ----
tabItem(
  tabName = "tools",  # h3("Data"),
  fluidRow(
    column(1, img(src = "SaltsR_hexsticker.png", height = 100, width = 90, align = "left")), 
    column(5, h1("Salt tools"), 
           p("Use this tool to upload data and analyse salt data from analysis. 
        Salt ion concentrations are inputted as ppm from ion chromatography or other analytical method.",
        tags$a(href="https://www.saltwiki.net/index.php/Analysis_of_Salts", "Saltwiki"))),
    column(6, 
           shinydashboard::box(
             title = "Salt input instructions (coming...)", status = "primary",
             collapsible = TRUE, collapsed = TRUE, width = 12,
             solidHeader = TRUE, background = "light-blue",
             HTML('<iframe width="400" height="200" src="https://www.youtube.com/embed/rWenD7u4SOg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>')))), 
  
  p("Single input: Use this tool for generating the input data for the ECOS-RUNSALT software."),  
  # p("The tool can create the ECOS-RUNSALT input for a single salt concentration measurement."), 
  fluidRow(
    shinydashboard::box(
      title = "Single sample input", status = "primary", 
      collapsible = TRUE, collapsed = TRUE, width = 12, 
      solidHeader = TRUE, background = "light-blue",
      fluidRow(
        column(3, 
               uiOutput("inst_name"),
               uiOutput("inst_country"),
               uiOutput("sample_location"),  
               uiOutput("sample_city"),
               uiOutput("sample_code"), 
               uiOutput("sample_date"), 
        ), 
        column(3, 
               uiOutput("user_name"), 
               uiOutput("user_email"), 
               uiOutput("sample_material"), 
               uiOutput("sample_description"),
               uiOutput("sample_depth"), 
               uiOutput("sample_height"), 
        ),
        column(6, leaflet::leafletOutput("leaflet_map1"), 
               column(6, uiOutput("sample_lat")), column(6, uiOutput("sample_lon")))),  
      fluidRow(tableOutput("salt_datatable_meta")),
      fluidRow(
        column(4, uiOutput("sample_name")), 
        column(1, )),
      fluidRow(
        column(3, uiOutput("water_ml")), 
        column(2, uiOutput("chloride_ppm")),
        column(2, uiOutput("nitrate_ppm")),
        column(2, uiOutput("sulfate_ppm")),
        column(2, )),
      fluidRow(
        column(3, uiOutput("dry_g")), 
        column(2, uiOutput("sodium_ppm")),
        column(2, uiOutput("potassium_ppm")),
        column(2, uiOutput("calcium_ppm")),
        column(2, uiOutput("magnesium_ppm")),
      ), 
      fluidRow(
        p("Table of ppm values inputted"),
        tableOutput("salt_datatable_ppm"), 
        p("Table of ion weights of the inputted data"),
        tableOutput("salt_datatable_input_wt"),
        p("Table of ion weights corrected for gypsum content"),
        tableOutput("salt_datatable_results_wt")), 
      fluidRow(
        column(1, actionButton("sample_calc", "Calculate")),
        column(2, uiOutput("salt_sample_select")),
        column(2, uiOutput("ggplot_color")), 
        column(2, uiOutput("ggplot_fontsize"))),
      fluidRow(
        column(6, plotOutput("salt_ppm_ggplot1")), 
        column(6, plotOutput("salt_ppm_ggplot2")),  
        column(12, plotOutput("salt_ppm_ggplot3")), 
        uiOutput("salt_select_results"),
        column(12, tableOutput("salt_datatable_results_long"))))),
  p("Mutliple input: Use this tool for generating the input data for the ECOS-RUNSALT software from a template."),
  fluidRow(
    shinydashboard::box(
      title = "Input for ECOS RUNSALT", status = "primary", 
      collapsible = TRUE, collapsed = TRUE, width = 12, 
      solidHeader = TRUE, background = "light-blue",
      fluidRow( 
        column(4,
               downloadButton("download_salt_template", "1) Download template & example"), h2(""),
               fileInput("salt_file_upload", NULL, accept = c(".csv", ".tsv"), 
                         buttonLabel = "2) Browse...",  placeholder = "Upload template"),
               downloadButton("salt_data_download_results", "3) Download results (csv)")),
        column(6, 
               #p("1) Download the template and use this to upload your salt data."), 
               #p("2) Select the number of rows to view and download the results for RUNSALT."),
               column(6, textInput("input_xl_sheet", "Select Excel sheet name", "test")),
               column(6, numericInput("n_preview_upload", "Preview number of lines", value = 3, min = 1, step = 1)))),
      # column(4, ),
      fluidRow(tableOutput("salt_upload_data_head")),
      
      column(6, 
             uiOutput("ECOS_RUNSALT_select_sample"),
             plotOutput("ECOS_ggplot"),
             tableOutput("ECOS_table"), 
             downloadButton("ECOS_RUSALT_output", "Download output for ECOS RUNSALT")), 
      column(6, )
    )),
  p("ECOS RUNSALT output - Tool to process data from the ECOS RUNSALT software,", tags$a(href="http://science.sdf-eu.org/runsalt/", "Price (2000) and Bionda (2005)")), 
  fluidRow(
    shinydashboard::box(
      title = "ECOS RUNSALT output", status = "primary",
      collapsible = TRUE, collapsed = TRUE, width = 12,
      solidHeader = TRUE, background = "light-blue", 
      column(12, fileInput("runsalt_file_upload", NULL, accept = c("text/plain"))),
      column(5, 
             uiOutput("ecos_env_name"), 
             uiOutput("ecos_env_params"), 
             uiOutput("ecos_env_value"),
             tableOutput("runsalt_upload_data_head")),
      column(7, plotOutput("runsalt_ggplot")))),
), # Data tab
#
# Analysis (ECOS RUNSALT) tab UI ----
tabItem(
  tabName = "analysis",
  fluidRow(
    column(1, img(src = "SaltsR_hexsticker.png", height = 100, width = 90, align = "left")),
    column(5, h2("Managing and predicting risks"),  
    ), 
    # column(6, # p("How to use the ECOS RUNSALT sotfware"), 
    #        shinydashboard::box(
    #          title = "ECOS RUNSALT instructions (coming...)", status = "primary",
    #          collapsible = TRUE, collapsed = TRUE, width = 12,
    #          solidHeader = TRUE, background = "light-blue",
    #          ))
  ),
  # box(tags$img(src = "ECOS RUNSALT instructions.png")), # 
  br(),
  p("Tool to predict if salt formation will occur from the climate."),
  fluidRow(
    shinydashboard::box(
      title = "Climate risks", status = "primary",
      collapsible = TRUE, collapsed = FALSE, width = 12,
      solidHeader = TRUE, background = "light-blue", 
      column(5, 
             uiOutput("worldmet_latlon"), 
             p("2) Click button to search for available weather station data"),
             uiOutput("worldmet_button"), br(),
             p("3) Select site"),
             uiOutput("worldmet_site"),
             p("4) Select year"),
             uiOutput("worldmet_year"),
             p("5) Load and graph data"), 
             uiOutput("worldmet_graphbutton"),
             p("6) Download weather station data"),
             downloadButton("worldmet_datadownload", "Download")), 
      column(7, leaflet::leafletOutput("worldmet_leaflet_map")),
      p("Weather stations within 50km radius"),
      fluidRow(column(12, tableOutput("worldmet_live_metadata"))),
      p("Graph of temperture and humidity is presented."),
      numericRangeInput("worldmet_RHexceed", "RH equilibrium", width = '400px', value = c(65, 75)), 
      fluidRow(column(12, plotOutput("worldmet_ggplot"))), br(),
      tableOutput("worldmet_exceedance_table")
    )),
  fluidRow(
    shinydashboard::box(
      title = "Climate analysis", status = "primary",
      collapsible = TRUE, collapsed = TRUE, width = 12,
      solidHeader = TRUE, background = "light-blue", 
      fluidRow(column(6, plotOutput("worldmet_ggTRHplot")), 
               column(6, plotOutput("worldmet_ggDensityplot"))), 
      fluidRow(column(12, plotOutput("worldmet_openair_timeVariation"))), br(),
      fluidRow(column(6, plotOutput("worldmet_openair_calendarPlot")), # 
               column(6, plotOutput("worldmet_openair_trendLevel"))),
      fluidRow(column(2, uiOutput("worldmet_select_pollutant"))), 
    )), 
  textOutput("openair_citation")
) # Analysis (ECOS) tab
  )


# UI ----
ui <-
  dashboardPage(
    skin = "blue",
    dashboardHeader(titleWidth = 250, title = "Salt weathering tool"),
    dashboardSidebar(width = 140, collapsed = FALSE, sidebar),
    dashboardBody(body)
  )


# Server ----
server <- function(input, output) {
  
  
  # Salt input - Data upload / download ----
  
  salt_upload_data <- reactive({
    req(input$salt_file_upload)
    ext <- tools::file_ext(input$salt_file_upload$name)
    switch(ext,
           csv = vroom::vroom(input$salt_file_upload$datapath, delim = ","),
           tsv = vroom::vroom(input$salt_file_upload$datapath, delim = "\t"),
           xlsx = readxl::read_excel(input$salt_file_upload$datapath, 
                                     sheet = input$input_xl_sheet),
           xlx = readxl::read_excel(input$salt_file_upload$datapath, 
                                    sheet = input$input_xl_sheet),
           validate("Invalid file; Please upload a .csv, .xlsx, .xls or .tsv file using the template"))
  })
  output$salt_upload_data_head <- renderTable({
    observe("salt_input_column_filter")
    salt_upload_data() %>%
      head(input$n_preview_upload) 
  })
  salt_data <- reactive({
    salt_upload_data() %>%
      setNames(salt_names$change_to[match(names(salt_upload_data()), salt_names$change_from)]) %>% 
      # SaltsR::salt_calcs(sample_name = "sample_code")
      fun_salt_calcs(sample_name = "sample_code") 
  })
  salt_data_ECOS <- reactive({
    salt_data() %>%
      mutate(ECOS_sample_name = 
               paste0(row_number(), "_", inst_abbr, sample_year, sample_month, sample_code)) %>%
      select(ECOS_sample_name, ends_with("_MOLkg")) %>%
      pivot_longer(-ECOS_sample_name) %>%
      separate(name, sep = "_", into = c("Salt", "Output"))
  })
  output$salt_data_download_results <- downloadHandler(
    filename = function() {
      paste0(input$salt_file_upload, ".csv")
    },
    content = function(salt_file_upload) {
      # readr::write_excel_csv(salt_data(), salt_file_upload)
      vroom::vroom_write(salt_data(), salt_file_upload, delim = ",")
    })
  output$download_salt_template_csv <- downloadHandler(
    filename = "salt_input_template.csv",
    content = function(file) {
      vroom::vroom_write(salt_input_template, file, delim = ",")
      # readr::write_excel_csv(salt_input_template, file)
    })
  # salt_input_template <- read_excel("Salt_input_template.xlsx")
  output$download_salt_template <- downloadHandler(
    filename = "salt_input_template.csv",
    content = function(file) write.csv(salt_input_template, file),  
    contentType = "text/csv"
  )
  
  
  
  # ECOS RUNSALT output ----
  
  output$ECOS_RUNSALT_select_sample <- renderUI({
    req(salt_data_ECOS())
    selectInput("ECOS_RUNSALT_select_sample", "Select samples", multiple = TRUE,
                choices = salt_data_ECOS()$ECOS_sample_name %>% unique(), 
                selected = salt_data_ECOS()$ECOS_sample_name[1])
  })
  output$ECOS_table <- renderTable({
    salt_data_ECOS() %>%
      filter(ECOS_sample_name %in% c(input$ECOS_RUNSALT_select_sample))
  }, digits = 6)
  output$ECOS_ggplot <- renderPlot({
    req(input$ECOS_RUNSALT_select_sample)
    salt_data_ECOS() %>%
      filter(ECOS_sample_name %in% c(input$ECOS_RUNSALT_select_sample)) %>%
      ggplot() + 
      geom_bar(aes(x = ECOS_sample_name, y = value, fill = Salt),
               position = "stack", stat = "identity", alpha = 0.8) +
      labs(x = "", y = "Weight corrected for RUNSALT") + 
      coord_flip() + 
      scale_fill_viridis(discrete = TRUE) +
      hrbrthemes::theme_tinyhand()
  })# , bg = "transparent")
  ecos_file <- eventReactive(input$ECOS_RUNSALT_select_sample, {
    salt_data_ECOS() %>%
      filter(ECOS_sample_name %in% c(input$ECOS_RUNSALT_select_sample))
  })
  output$ECOS_RUSALT_output <- downloadHandler(
    filename = function() {
      paste0(input$ECOS_RUNSALT_select_sample, ".csv")
    },
    content = function(ecos_file) {
      vroom::vroom_write(ecos_file() %>% select(Salt, value), 
                         ecos_file, delim = ";")
    })
  
  
  # Salt data single ----
  
  # Salt data single graphs ----
  
  salt_ppm <- eventReactive(input$sample_calc, {
    tibble(
      sample_name = as.character(input$sample_name),
      dry_g = as.numeric(input$dry_g),
      water_ml = as.numeric(input$water_ml),
      chloride_ppm = as.numeric(input$chloride_ppm),
      nitrate_ppm = as.numeric(input$nitrate_ppm),
      sulfate_ppm = as.numeric(input$sulfate_ppm),
      sodium_ppm = as.numeric(input$sodium_ppm),
      potassium_ppm = as.numeric(input$potassium_ppm),
      calcium_ppm = as.numeric(input$calcium_ppm),
      magnesium_ppm = as.numeric(input$magnesium_ppm))
  })
  output$salt_datatable_ppm <- renderTable({
    salt_ppm()
  })
  #
  salt_results <- reactive({
    salt_ppm() %>%
      fun_salt_calcs(sample_name = sample_name)
    # SaltsR::salt_calcs(sample_name = "sample_code")
  })
  salt_combined <- reactive({
    salt_data() # %>% bind_rows(salt_results())
  })
  salt_results_long <- reactive({
    salt_combined() %>%
      # filter(sample_name == input$salt_sample_select) %>%
      # salt_results() %>%
      # select(sample_name, ends_with("_Wt", ignore.case = FALSE)) %>%
      pivot_longer(-sample_name) %>%
      separate(name, sep = "_", into = c("Salt", "Output"))
  })
  #
  output$salt_datatable_results_long <- renderTable({
    salt_results_long() 
  }, digits = 6)
  output$salt_datatable_input_wt <- renderTable({
    salt_results() %>% 
      select(c(sample_name, Chloride_wt, Nitrate_wt, Sulfate_wt, 
               Sodium_wt, Potassium_wt, Calcium_wt, Magnesium_wt, total_salt_wt))
  }, digits = 6)
  output$salt_datatable_results_wt <- renderTable({
    salt_results() %>% 
      select(c(sample_name, Chloride_Wt, Nitrate_Wt, Sulfate_Wt, 
               Sodium_Wt, Potassium_Wt, Calcium_Wt, Magnesium_Wt, 
               total_Wt, total_gypsum_Wt))
  }, digits = 6)
  output$salt_sample_select <- renderUI({
    selectInput("salt_sample_select", "Select data", choices = c(unique(salt_results()$sample_name)))
  })
  output$ggplot_color <- renderUI({
    radioButtons("ggplot_color", "Select colour", choices = c("A", "B", "C", "D"), 
                 selected = "D", inline = TRUE)
  })
  output$ggplot_fontsize <- renderUI({
    numericInput("ggplot_fontsize", "Select font size", value = 14)
  })
  output$salt_ppm_ggplot1 <- renderPlot({
    req(input$sample_calc)
    p <- salt_results() %>% 
      select(sample_name, Chloride_wt, Nitrate_wt, Sulfate_wt, 
             Sodium_wt, Potassium_wt, Calcium_wt, Magnesium_wt, total_salt_wt) %>%
      pivot_longer(-sample_name) %>%
      separate(name, sep = "_", into = c("Salt", "Weight")) %>%
      ggplot() + 
      geom_bar(aes(x = Salt, y = value, fill = Salt), 
               position = "dodge", stat = "identity", alpha = 0.8) +
      labs(x = "", y = "Inputed weight", title = "Sample data") + 
      coord_flip() +
      facet_wrap(~ sample_name) + 
      scale_fill_viridis(discrete = TRUE, option = input$ggplot_color) + 
      hrbrthemes::theme_tinyhand(base_size = input$ggplot_fontsize) #  14)
    return(p) # ggplotly(p)
  }) # , bg = "transparent")
  output$salt_ppm_ggplot2 <- renderPlot({
    req(input$sample_calc)
    p <- salt_results() %>%
      select(sample_name, ends_with("_Wt", ignore.case = FALSE)) %>%
      pivot_longer(-sample_name) %>%
      separate(name, sep = "_", into = c("Salt", "Weight")) %>% 
      ggplot() + 
      geom_bar(aes(x = Salt, y = value, fill = Salt), 
               position = "dodge", stat = "identity", alpha = 0.8) +
      labs(x = "", y = "Weight corrected for RUNSALT", title = "Corrected for RUNSALT") + 
      coord_flip() + 
      facet_wrap(~ sample_name) + 
      scale_fill_viridis(discrete = TRUE, option = input$ggplot_color) + 
      hrbrthemes::theme_tinyhand(base_size = input$ggplot_fontsize)
    return(p) # ggplotly(p)
  }) # , bg = "transparent")
  output$salt_ppm_ggplot3 <- renderPlot({
    req(input$sample_calc)
    p <- salt_results() %>%
      select(sample_name, ends_with("_Wt", ignore.case = FALSE)) %>%
      pivot_longer(-sample_name) %>%
      separate(name, sep = "_", into = c("Salt", "Weight")) %>% 
      ggplot() + 
      geom_bar(aes(x = sample_name, y = value, fill = Salt), 
               position = "stack", stat = "identity", alpha = 0.8) +
      labs(x = "", y = "Weight corrected for RUNSALT") + 
      coord_flip() + 
      facet_wrap(~ sample_name) + 
      scale_fill_viridis(discrete = TRUE, option = input$ggplot_color) + 
      hrbrthemes::theme_tinyhand(base_size = input$ggplot_fontsize)
    return(p)
  }) # , bg = "transparent")
  output$salt_select_results <- renderUI({
    req(salt_results())
    selectInput(
      "salt_select_results", "Select results to display", 
      choices = names(salt_results()), multiple = TRUE, 
      selected = c(
        "Chloride_Wt" ,"Nitrate_Wt", "Sulfate_Wt", 
        "Sodium_Wt", "Potassium_Wt", "Calcium_Wt", "Magnesium_Wt", 
        "total_Wt", "total_gypsum_Wt"))
  })
  output$salt_datatable_results_selected <- renderTable({
    salt_results() %>% 
      select(c(sample_name, input$salt_select_results))
  }, digits = 6)
  
  # Salt data input ----
  
  output$sample_name <- renderUI({
    textInput("sample_name", "Sample name", "Sample name")
  })
  output$water_ml <- renderUI({
    numericInput("water_ml", "Water added for IC (ml)", value = 100, min = 0)
  })
  output$dry_g <- renderUI({
    numericInput("dry_g", "Dry sample weight for IC (g)", value = 1, min = 0)
  })
  output$chloride_ppm <- renderUI({
    numericInput("chloride_ppm", "Chloride (ppm)", value = 66.824, min = 0)
    # shinyWidgets::numericInputIcon("chloride_ppm", "Chloride (ppm)", 66.824, 0, "cube"))
  })
  output$nitrate_ppm <- renderUI({
    numericInput("nitrate_ppm", "Nitrate (ppm)", value = 332.956, min = 0)
  })
  output$sulfate_ppm <- renderUI({
    numericInput("sulfate_ppm", "Sulfate (ppm)", value = 87.221, min = 0)
  })
  output$sodium_ppm <- renderUI({
    numericInput("sodium_ppm", "Sodium (ppm)", value = 21.471, min = 0)
  })
  output$potassium_ppm <- renderUI({
    numericInput("potassium_ppm", "Potassium (ppm)", value = 211.358, min = 0)
  })
  output$calcium_ppm <- renderUI({
    numericInput("calcium_ppm", "Calcium (ppm)", value = 75.594, min = 0)
  })
  output$magnesium_ppm <- renderUI({
    numericInput("magnesium_ppm", "Magnesium (ppm)", value = 7.582, min = 0)
  })
  
  
  # Salt metadata single input ----
  
  salt_metadata <- reactive({
    salt_metadata <- tibble::tibble(
      Institute = input$inst_name,
      User = input$user_name,
      Email = input$user_email, 
      Location = input$sample_location, 
      Code = input$sample_code, 
      Date = input$sample_date, 
      Latitude = input$sample_lat,
      Longitude = input$sample_lon, 
      Material = input$sample_material, 
      Height = input$sample_height,
      Depth = paste0(input$sample_depth[1], "to", input$sample_depth[2]))
    # return(salt_metadata)
  })
  output$salt_datatable_meta <- renderTable({
    salt_metadata()
  })
  
  output$inst_name <- renderUI({
    shinyWidgets::textInputIcon(
      "inst_name", "Institute name", value = "KIK_IRPA", icon = icon("edit")) #
  })
  output$inst_country <- renderUI({
    shinyWidgets::textInputIcon(
      "inst_country", "Institute country", value = "BE", icon = icon("edit")) # 
  })
  output$user_name <- renderUI({
    shinyWidgets::textInputIcon(
      "user_name", "User name", value = "KIK_IRPA", icon = icon("edit"))
  })
  output$user_email <- renderUI({
    shinyWidgets::textInputIcon(
      "user_email", "User email", value = "@", icon = icon("email"))
  })
  output$sample_location <- renderUI({
    shinyWidgets::textInputIcon(
      "sample_location", "Sample location", value = "KIK_IRPA", 
      icon = icon("edit"))
  })
  output$sample_city <- renderUI({
    shinyWidgets::textInputIcon(
      "sample_city", "Sample city", value = "Brussels", icon = icon("edit"))
  })
  output$sample_code <- renderUI({
    shinyWidgets::textInputIcon(
      "sample_code", "Sample code", value = "X159", icon = icon("edit"))
  })
  output$sample_date <- renderUI({
    shinyWidgets::airMonthpickerInput(
      "sample_date", "Sample date", value = today(), 
      todayButton = TRUE, addon = "left") 
  })
  output$sample_lat <- renderUI({
    shinyWidgets::numericInputIcon(
      "sample_lat", label = "Latitude", 
      value = 50.842662, step = 0.001,  
      icon = list(icon("compass"))) 
  })
  output$sample_lon <- renderUI({
    shinyWidgets::numericInputIcon(
      "sample_lon", label = "Longitude", 
      value = 4.393407, step = 0.001,
      icon = list(icon("compass"))) 
  })
  output$sample_material <- renderUI({
    pickerInput(
      "sample_material", "Sample material", 
      selected = "Brick", 
      choices = 
        c("Brick", "Stone", "Mortar", "Plaster", "Render", "Concrete", "Other"),
      options = pickerOptions(
        header = "",  icon = icon("edit")
      ))
  })
  output$sample_description <- renderUI({
    textInputIcon(
      "sample_description", "Sample description", "If selected 'Other'",
      icon = icon("edit"))
  })
  output$sample_depth <- renderUI({
    shinyWidgets::numericRangeInput(
      "sample_depth", "Sample depth (cm)", value = c(0, 2), separator = "to")
  })
  output$sample_height <- renderUI({
    shinyWidgets::numericInputIcon(
      "sample_height", "Sample height (cm)", value = 0, step = 0.1, 
      icon = icon("codepen"))
  })
  
  
  # # ECOS RUNASLT data analysis tab ----
  # RUNSALT - Data upload / download ----
  
  runsalt_upload_data <- reactive({
    req(input$runsalt_file_upload)
    read_table2(input$runsalt_file_upload$datapath, col_names = FALSE)
  })
  output$ecos_env_params <- renderUI({
    textInput("ecos_env_name", "Sample name", "Enter sample name")
  })
  output$ecos_env_params <- renderUI({
    radioButtons("ecos_env_params", "Constant environmental parameter", 
                 selected = "RH", choices = c("Temp", "RH"), inline = TRUE)
  })
  output$ecos_env_value <- renderUI({
    numericInput("ecos_env_value", "Environmental parameter value", value = 20)
  })
  runsalt_data_long <- reactive({
    runsalt_upload_data() %>% 
      pivot_longer(-X1) %>% 
      separate(X1, sep = "_", into = c("Salt", "Variable")) %>%
      drop_na(value) %>%
      dplyr::select(-name) 
  })
  runsalt_data_wide <- reactive({
    runsalt_data_long() %>% 
      pivot_wider(names_from = Variable, values_from = value) %>% 
      unnest(c(X, Y)) %>% 
      group_by(Salt) 
  })
  runsalt_data <- reactive({
    runsalt_data_wide() %>% 
      mutate(diffY = Y - lag(Y, 1), 
             diffY2 = diffY - lag(diffY, 1), 
             RH_equilibrium = ifelse(diffY2 > 0, lag(X, 1), ""), 
             RH_equilibrium = ifelse(diffY2 == "NA", NA, RH_equilibrium), 
             Crystallisation = ifelse(X == max(X, na.rm = TRUE), X, NA)) %>%
      dplyr::select(-diffY, -diffY2)
  })
  runsalt_data_head <- reactive({
    runsalt_data() %>%
      summarise(RH_equilibrium = max(RH_equilibrium, na.rm = TRUE)) 
  })
  output$runsalt_upload_data_head <- renderTable({
    req(runsalt_data())
    runsalt_data_head()
  })
  output$runsalt_ggplot <- renderPlot({
    runsalt_data() %>% 
      ggplot(aes(X, Y, col = Salt)) + 
      geom_line(size = 1.5) +
      # ggrepel::geom_label_repel(aes(label = Deliquescence)) +
      ggrepel::geom_label_repel(aes(label = Crystallisation)) +
      labs(x = input$ecos_env_params, y = "Amount", 
           title = paste0("Salt output: ", input$ecos_env_name), 
           subtitle = paste0(
             ifelse(input$ecos_env_value == "Temp", "RH", "Temp"), " = ", input$ecos_env_value),
           caption = "Price (2000) and Bionda (2005)") + 
      scale_color_viridis_d() + 
      hrbrthemes::theme_tinyhand(base_size = 14) 
  }) # , bg = "transparent")
  
  
  # Worldmet data ----
  
  library(worldmet); library(leaflet)
  
  output$worldmet_latlon <- renderUI({
    shinyWidgets::numericRangeInput(width = '400px',
                                    "worldmet_latlon", "1) Find weather stations by latitude and longitude", 
                                    value = c(50.842662, 4.393407), separator = ",") 
  })
  output$worldmet_button <- renderUI({
    actionButton("worldmet_button", "Search weather stations")
  })
  worldmet_meta <- eventReactive(input$worldmet_button, { 
    # getMeta(site = input$worldmet_site)
    getMeta(lat = input$worldmet_latlon[2], lon = input$worldmet_latlon[1])
  })
  worldmet_meta_map <- eventReactive(input$worldmet_button, { 
    # getMeta(site = input$worldmet_site, returnMap = TRUE)
    getMeta(lat = input$worldmet_latlon[2], lon = input$worldmet_latlon[1], returnMap = TRUE)
  })
  output$worldmet_live_metadata <- renderTable({
    worldmet_meta()
  })
  output$worldmet_leaflet_map <- leaflet::renderLeaflet({
    worldmet_meta_map()
  })
  output$worldmet_site <- renderUI({
    req(worldmet_meta())
    selectInput("worldmet_site", 
                "Select site: use map and table below (dist = Distance)", 
                choices = worldmet_meta()$station,  multiple = TRUE)
  })
  output$worldmet_year <- renderUI({
    req(worldmet_meta())
    shinyWidgets::airYearpickerInput(
      "worldmet_year", "Select years of data", multiple = TRUE, clearButton = TRUE) 
  })
  output$worldmet_graphbutton <- renderUI({
    req(worldmet_meta())
    actionButton("worldmet_graphbutton", "Graph data")
  })
  worldmet_data <- eventReactive(input$worldmet_graphbutton, {
    data_NOAA <- worldmet_meta() %>% filter(station %in% c(input$worldmet_site)) %>% pull(code)
    importNOAA(hourly = TRUE, n.cores = 1, path = NA, 
               code = c(data_NOAA), year = lubridate::year(input$worldmet_year)) %>%
      dplyr::mutate(
        RH_eq1 = input$worldmet_RHexceed[1],
        RH_eq2 = input$worldmet_RHexceed[2],
        RH_exceed_eq1 = ifelse(RH > RH_eq1, 1, 0),
        RH_exceed_eq2 = ifelse(RH > RH_eq2, 1, 0), 
        DewPoint_exceed <- ifelse(dew_point < air_temp, 1, 0), 
        FrostPoint_exceed <- ifelse(air_temp < 1, 1, 0))
  })
  worldmet_exceedance <- eventReactive(input$worldmet_graphbutton, {
    worldmet_data() %>%
      group_by(station) %>%
      summarise(
        RH_exceed_eq1 = mean(RH_exceed_eq1, na.rm = TRUE),
        RH_exceed_eq2 = mean(RH_exceed_eq2, na.rm = TRUE),
        DewPoint_exceed = mean(DewPoint_exceed, na.rm = TRUE),
        FrostPoint_exceed = mean(FrostPoint_exceed, na.rm = TRUE))
  })
  output$worldmet_exceedance_table <- renderTable({
    worldmet_exceedance()
  })
  output$worldmet_ggplot <- renderPlot({
    req(worldmet_data())
    worldmet_data() %>%
      ggplot() + 
      geom_line(aes(x = date, y = air_temp, col = air_temp)) + 
      geom_line(aes(x = date, y = RH, col = RH)) + 
      geom_hline(aes(yintercept = input$worldmet_RHexceed[1])) + 
      geom_hline(aes(yintercept = input$worldmet_RHexceed[2])) + 
      geom_text(aes(x = min(date), y = input$worldmet_RHexceed[1], label = "Salt 1", vjust = -1)) +
      geom_text(aes(x = min(date), y = input$worldmet_RHexceed[2], label = "Salt 2", vjust = -1)) + 
      geom_rug(aes(x = date, y = RH_exceed_eq1, col = RH_exceed_eq1), outside = TRUE) +
      # geom_rug(aes(x = date, y = RH_exceed_eq2, col = RH_exceed_eq2)) +
      # geom_rug(aes(x = date, y = DewPoint_exceed, col = DewPoint_exceed)) + 
      # geom_rug(aes(x = date, y = FrostPoint_exceed, col = FrostPoint_exceed)) +
      scale_colour_viridis_c(option = "D") + 
      labs(x = "", y = "", legend = "") + 
      facet_wrap(~ station) + 
      hrbrthemes::theme_tinyhand() + 
      theme(legend.title = element_blank()) 
  }) 
  output$worldmet_exceed_ggplot <- renderPlot({
    req(worldmet_exceedance())
    worldmet_exceedance() %>%
      ggplot() + 
      geom_autohistogram() + 
      scale_colour_viridis_c(option = "D") + 
      labs(x = "", y = "", legend = "") + 
      facet_wrap(~ station) + 
      hrbrthemes::theme_tinyhand() + 
      theme(legend.title = element_blank()) 
  }) 
  output$worldmet_select_pollutant <- renderUI({
    req(worldmet_data())
    selectInput("worldmet_select_pollutant", "Select variable", choices = names(worldmet_data()), 
                selected = "RH")
  })
  output$worldmet_openair_timeVariation <- renderPlot({
    req(worldmet_data())
    openair::timeVariation(
      worldmet_data(), pollutant = input$worldmet_select_pollutant, type = "station",
      statistic = "median", col = "firebrick", site = input$station)
  })
  output$worldmet_openair_trendLevel <- renderPlot({
    req(worldmet_data())
    openair::trendLevel(
      worldmet_data(), pollutant = input$worldmet_select_pollutant, x = "month", y = "hour", 
      type = "station")
  })
  output$worldmet_openair_calendarPlot <- renderPlot({
    req(worldmet_data())
    openair::calendarPlot(
      worldmet_data(), pollutant = input$worldmet_select_pollutant, 
      breaks = c(0, 20, 30, 70, 80),
      labels = c("Very low", "Low", "High", "Very High"), annotate = "wd", 
      cols = c("lightblue", "green", "yellow",  "red"), statistic = "mean"
    )
  })
  output$worldmet_ggTRHplot <- renderPlot({
    req(worldmet_data())
    worldmet_data() %>%
      mutate(temp_mean = mean(air_temp, na.rm = TRUE),
             rh_mean = mean(RH, na.rm = TRUE)) %>%
      ggplot() + 
      geom_point(aes(x = air_temp, y = RH, fill = station, col = station), alpha = 0.5) +  
      # geom_rect(aes(xmin = 12, xmax = 25, ymin = 50, ymax = 65), 
      #           col = "green", fill = "transparent", size = 2) + 
      # ggforce::geom_mark_ellipse(aes(x = temp_mean, y = rh_mean, fill = station, label = station), 
      #                           con.cap = 0, con.colour = "grey", na.rm = TRUE) + 
      # ggforce::geom_mark_hull(aes(x = temp_mean, y = rh_mean, fill = station, label = station), 
      #                            con.cap = 0, con.colour = "grey", na.rm = TRUE) + 
      # coord_cartesian(xlim = c(-20, 40), ylim = c(0, 100)) + 
      labs(x = "Temperature (C)", y = "Humidity (%rh)" ) + #, 
      facet_wrap(~ station) + 
      hrbrthemes::theme_tinyhand() +
      theme(plot.title = element_blank(),  
            legend.position = "none", 
            axis.title.x = element_blank(), 
            axis.text.x = element_blank(), axis.ticks.x = element_blank()) 
  })
  output$worldmet_ggDensityplot <- renderPlot({
    req(worldmet_data())
    worldmet_data() %>% 
      ggplot() + 
      geom_density(aes(air_temp), fill = "hotpink", col = "hotpink", alpha = 0.5) +  
      geom_density(aes(RH), fill = "cornflowerblue", col = "cornflowerblue", alpha = 0.5) +  
      labs(x = "Temperature and humidity", y = "Density" ) + #, 
      facet_wrap(~ station) + 
      hrbrthemes::theme_tinyhand() +
      theme(legend.position = "none") 
  })
  output$openair_citation <- renderText({
    # citation("openair")
    "Carslaw, D. C. and K. Ropkins, (2012) openair --- an R package for air quality data analysis.
  Environmental Modelling & Software. Volume 27-28, 52-61."
  })
  output$worldmet_datadownload <- downloadHandler(
    filename = function() {
      paste0("worldmet_data", ".csv")
    },
    content = function(worldmet) {
      vroom::vroom_write(worldmet_data(), worldmet, delim = ",")
    })
  
  
  # Open weather ----
  
  # openweather <- reactive({
  # openweather_centre <- "lat=50.8&lon=4.39&cnt=10&" # KIK-IRPA
  openweather_centre <- reactive({
    paste0("lat=", input$sample_lat, "&lon=", input$sample_lon, "&cnt=", 10)})
  #
  openweather_req <- reactive({
    jsonlite::fromJSON(
      paste0(
        "http://api.openweathermap.org/data/2.5/find?", 
        openweather_centre(), openweather_id))
  })
  
  openweather_data <- reactive({ 
    openweather_data <- 
      tibble(
        date = openweather_req()$list$dt %>% lubridate::as_datetime(),
        name = openweather_req()$list$name,
        lat = openweather_req()$list$coord$lat,
        lng = openweather_req()$list$coord$lon,
        RH = openweather_req()$list$main$humidity,
        Temp = openweather_req()$list$main$temp - 273.16,
        Feels = openweather_req()$list$main$feels_like - 273.16,
        temp_min = openweather_req()$list$main$temp_min - 273.16,
        temp_max = openweather_req()$list$main$temp_max - 273.16,
        pressure = openweather_req()$list$main$pressure,
        wind_speed = openweather_req()$list$wind$speed,
        wind_deg = openweather_req()$list$wind$deg,
        clouds = openweather_req()$list$clouds$all )
    return(openweather_data)
  })
  
  # Pollution (openair) ----
  # library(openair)
  
  
  # Leaflet maps ----
  
  # leaflet_server("leaflet_map2", df = salt_metadata(), weather_df = openweather_data())
  
  output$leaflet_map1 <- renderLeaflet({
    icon_sample_location <- makeAwesomeIcon(
      icon = "university", markerColor = "blue", library = "fa", iconColor = "grey50")
    
    sample_map <-
      leaflet() %>%
      addProviderTiles(
        providers$Stamen.TonerLite, group = "Lite") %>%
      addProviderTiles(
        providers$CartoDB.DarkMatter, group = "Dark") %>%
      addProviderTiles(
        providers$Esri.WorldImagery, group = "Satellite") %>%
      addProviderTiles(
        providers$OpenStreetMap, group = "Street") %>% 
      addAwesomeMarkers(
        data = salt_metadata(), group = "Salt",
        lat = ~Latitude, lng = ~Longitude, label = ~Location,
        popup = ~paste(
          "<b>", salt_metadata()$Location, "</b>", "<br>", "",
          salt_metadata()$Latitude, salt_metadata()$Longitude, "<br>", "",
          salt_metadata()$Date, "<br>", "",
          salt_metadata()$Material, ",", salt_metadata()$Height, ",",
          salt_metadata()$Depth, "<br>", "",
          salt_metadata()$Code, "<br>", ""), 
        icon = icon_sample_location, 
        labelOptions = labelOptions(textOnly = TRUE, textsize = "20px")) %>%
      addCircleMarkers(
        group = "Weather",
        data = openweather_data(),
        lng = ~lng, lat = ~lat,
        label = ~name,
        stroke = FALSE, weight = 3, radius = 4, fillOpacity = 0.9,
        popup = ~paste(
          "", "<b>", openweather_data()$name, "</b>", "<br>", "",
          openweather_data()$date, "<br>",
          "Temperature:", round(openweather_data()$Temp, digits = 1), "<br>",
          "Feels like:", round(openweather_data()$Feels, digits = 1), "<br>",
          "Humidity:", round(openweather_data()$RH, digits = 1), "<br>",
          "Wind speed:", openweather_data()$wind_speed, "<br>",
          "Wind direction:", openweather_data()$wind_deg, "<br>",
          "Cloud coverage:", openweather_data()$clouds),
        labelOptions = labelOptions(textOnly = TRUE, textsize = "15px")) %>%
      addMiniMap(toggleDisplay = TRUE, position = "bottomright", minimized = TRUE) %>%
      addLayersControl(
        baseGroups = c("Lite", "Dark", "Street", "Satellite"),
        overlayGroups = c("Salt", "Weather"),
        options = layersControlOptions(collapsed = TRUE)) # %>% hideGroup("Weather") 
    return(sample_map)
  })
  
  output$leaflet_map3 <- renderLeaflet({
    icon_sample_location <- makeAwesomeIcon(
      icon = "university", markerColor = "blue", library = "fa", iconColor = "grey50")
    
    sample_map <-
      leaflet() %>%
      addProviderTiles(
        providers$Stamen.TonerLite, group = "Lite") %>%
      addProviderTiles(
        providers$CartoDB.DarkMatter, group = "Dark") %>%
      addProviderTiles(
        providers$Esri.WorldImagery, group = "Satellite") %>%
      addProviderTiles(
        providers$OpenStreetMap, group = "Street") %>% 
      addAwesomeMarkers(
        data = salt_metadata(), group = "Salt",
        lat = ~Latitude, lng = ~Longitude, label = ~Location,
        popup = ~paste(
          "<b>", salt_metadata()$Location, "</b>", "<br>", "",
          salt_metadata()$Latitude, salt_metadata()$Longitude, "<br>", "",
          salt_metadata()$Date, "<br>", "",
          salt_metadata()$Material, ",", salt_metadata()$Height, ",",
          salt_metadata()$Depth, "<br>", "",
          salt_metadata()$Code, "<br>", ""), 
        icon = icon_sample_location, 
        labelOptions = labelOptions(textOnly = TRUE, textsize = "20px")) %>%
      addCircleMarkers(
        group = "Weather",
        data = openweather_data(),
        lng = ~lng, lat = ~lat,
        label = ~name,
        stroke = FALSE, weight = 3, radius = 4, fillOpacity = 0.9, 
        popup = ~paste(
          "", "<b>", openweather_data()$name, "</b>", "<br>", "",
          openweather_data()$date, "<br>",
          "Temperature:", round(openweather_data()$Temp, digits = 1), "<br>",
          "Feels like:", round(openweather_data()$Feels, digits = 1), "<br>",
          "Humidity:", round(openweather_data()$RH, digits = 1), "<br>",
          "Wind speed:", openweather_data()$wind_speed, "<br>",
          "Wind direction:", openweather_data()$wind_deg, "<br>",
          "Cloud coverage:", openweather_data()$clouds),
        labelOptions = labelOptions(textOnly = TRUE, textsize = "15px")) %>%
      addMiniMap(toggleDisplay = TRUE, position = "bottomright", minimized = TRUE) %>%
      addLayersControl(
        baseGroups = c("Lite", "Dark", "Street", "Satellite"),
        overlayGroups = c("Salt", "Weather"),
        options = layersControlOptions(collapsed = TRUE)) %>%
      hideGroup("Weather") 
    return(sample_map)
  })
  
  
  output$Instructions_select <- renderUI({
    prettyRadioButtons(
      "risk_img", label = "", choices = c("RUNSALT"), bigger = TRUE, 
      animation = "jelly", shape = "curve", outline = FALSE,  
      selected = "RUNSALT", inline = TRUE, width = "100%")
  })
  
  output$Instructions_RUNSALT <- renderImage({ 
    req(input$Instructions_select) 
    switch(input$Instructions_select,
           "RUNSALT" = list(src = "www/ECOS RUNSALT instructions.png")
    )}, deleteFile = FALSE)
  
  output$ucl_logo <- renderImage({
    outfile <- tempfile(fileext = '.png') 
    png(outfile, width = 400, height = 400)
    hist(rnorm(input$n))
    dev.off()
    list(src = outfile, alt = "This is alternate text")
  }) 
  
  output$kik_logo <- renderImage({
    
  })
  
}


# App ----
shinyApp(ui = ui, server = server)
